'use strict';

/**
 * Code provenance information generated by grunt-version-file. As of LF 1.1.0 and GVF 0.2.2 this includes:
 * - datestring
 * - npm_version
 * - git_describe
 */
module.exports = require('app/config/version.json');
