define(function(require) {
  'use strict';

  var q = require('q');

  var AppObj = require('js/app/obj');
  var logger = AppObj.logger.get('root/js/common/flash_message');

  AppObj.module('Common.Entities', function(Entities, AppObj, Backbone, Marionette, $, _) {
    require('js/base/entities');

    /**
     * Used to access a flash message stored on the server api_util_config.flash_message_key ('flash_message')
     */
    Entities.FlashMessage = AppObj.Base.Entities.ROnlyPersistentModel.extend({
      __name: 'FlashMessage',
      urlRoot: '/api/util/flash_message'
    });

    /**
     * Represents information about the application's code provenance, e.g. as generated by `grunt-version-file`
     */
    Entities.VersionInfo = AppObj.Base.Entities.ROnlyPersistentModel.extend({
      __name: 'VersionInfo',
      urlRoot: '/api/util/version_info'
    });

    /**
     * A client only model for instantiating an. No API or event requesters as it is a simple, client only model
     */
    Entities.ConfirmationPrompt = AppObj.Base.Entities.TransientModel.extend({
      __name: 'ConfirmationPrompt',
      defaults: {
        header: 'Please confirm',
        detail: 'Are you sure you want to do this?',
        confirm_text: 'Yes',
        reject_text: 'No'
      }
    });

    var API = {
      /**
       * Returns a promise for the flash message possibly available at /api/util/flash_message
       */
      get_flash_message_promise: function get_flash_message_promise() {
        logger.trace('API.get_flash_message_promise -- enter');
        var deferred = q.defer();
        var flash_message = new Entities.FlashMessage();
        flash_message.fetch({
          success: function success(flash_message_model) {
            logger.debug('API.get_flash_message_promise - success -- received: ' + flash_message_model);
            deferred.resolve(flash_message_model);
          },
          error: function error() { deferred.resolve(undefined); }
        });
        return deferred.promise;
      },

      /**
       * Returns a promise for the version info assumedly available at /api/util/version_info
       */
      get_version_info_promise: function get_version_info_promise() {
        logger.trace('API.get_version_info_promise -- enter');
        var deferred = q.defer();
        var version_info = new Entities.VersionInfo();
        version_info.fetch({
          success: function success(version_info_model) {
            logger.debug('API.get_version_info_promise - success -- received: ' + version_info_model);
            deferred.resolve(version_info_model);
          },
          error: function error() { deferred.resolve(undefined); }
        });
        return deferred.promise;
      }
    };

    AppObj.reqres.setHandler('common:entities:flashmessage', function() {
      return API.get_flash_message_promise();
    });

    AppObj.reqres.setHandler('common:entities:versioninfo', function() {
      return API.get_version_info_promise();
    });
  });

  return AppObj.Common.Entities;
});
